title: "RCL Identity"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
ga_tracking: G-R8D9K4GZVQ
ga_tracking_anonymize_ip: true
aux_links:
  "RCL Identity on GitHub":
    - "https://github.com/rcl-identity/docs"